### ISSUE TITLE
Create an AMI for uplink build and release action

### ISSUE THREAD

**Issue by de-sh** [bytebeamio/uplink#17]
Create an AMI for EC2 based build and release of uplink binary.

The AMI must support running full fledged [cross-rs/cross](https://github.com/cross-rs/cross) to build and publish uplink binaries along with each release. Which requires dockerd and cargo.

You can find more context in the [release.yml on build-release branch](https://github.com/bytebeamio/uplink/blob/build-release/.github/workflows/release.yml)

**Comment by 123vivekr** [comment]
Taking this up! Please assign this to me

**Comment by johnjacobkenny** [comment]
@de-sh the link to release.yml seems to be broken. Is this the link [https://github.com/bytebeamio/uplink/blob/main/.github/workflows/release.yml](https://github.com/bytebeamio/uplink/blob/main/.github/workflows/release.yml)
