### ISSUE TITLE
Regression: uplink fails if persistence is provided but persistence.max_file_size is not

### ISSUE THREAD

**Issue by bmcpt** [bytebeamio/uplink#94]
```
bridge_port = 8031
run_logcat = true

[persistence]
path = "/data/local/uplink/persistence"
```

This used to work previously but doesn't in latest main.

**Comment by de-sh** [comment]
This is the cause: https://github.com/bytebeamio/uplink/commit/5a04f292650138ce2ccb54c1dc79ed70e5b6a941, I have a fix in mind, let me try it out.
